export const films = [
    "El padrino",
    "El señor de los anillos: El retorno del rey",
    "El caballero oscuro",
    "Pulp Fiction",
    "El club de la pelea",
    "La lista de Schindler",
    "El bueno, el malo y el feo",
    "El gran dictador",
    "El Padrino II",
    "El viaje de Chihiro",
    "Cadena perpetua",
    "La vida es bella",
    "El sexto sentido",
    "Forrest Gump",
    "El resplandor",
    "Origen",
    "Matrix",
    "Interstellar",
    "El silencio de los corderos",
    "Seven",
    "El rey león",
    "Gladiador",
    "El señor de los anillos: La comunidad del anillo",
    "El club de los poetas muertos",
    "El gran Lebowski",
    "V de Vendetta",
    "Titanic",
    "El curioso caso de Benjamin Button",
    "Blade Runner",
    "Apocalipsis Now",
    "El exorcista",
    "La naranja mecánica",
    "Ciudad de Dios",
    "El laberinto del fauno",
    "El hombre elefante",
    "El rey pescador",
    "El bueno, el malo y el raro",
    "El pianista",
    "El gran hotel Budapest",
    "El efecto mariposa",
    "El show de Truman",
    "El golpe",
    "El ilusionista",
    "El aviador",
    "El origen del planeta de los simios",
    "El secreto de sus ojos",
    "El gran Gatsby",
    "El renacido",
    "El lobo de Wall Street",
    "El viaje más largo",
    "El discurso del rey",
    "El destino de Júpiter"
];

export const series = [
    "Breaking Bad",
    "Game of Thrones",
    "Stranger Things",
    "Friends",
    "The Office",
    "The Crown",
    "Sherlock",
    "Black Mirror",
    "Narcos",
    "House of Cards",
    "The Big Bang Theory",
    "The Walking Dead",
    "Lost",
    "Westworld",
    "Fargo",
    "True Detective",
    "Mindhunter",
    "Peaky Blinders",
    "Better Call Saul",
    "Dexter",
    "Homeland",
    "Money Heist (La Casa de Papel)",
    "The Witcher",
    "Ozark",
    "Vikings",
    "Stranger Things",
    "Chernobyl",
    "The Mandalorian",
    "The Haunting of Hill House",
    "Black Sails",
    "The Handmaid's Tale",
    "Gotham",
    "Sherlock",
    "Fargo",
    "True Detective",
    "Mindhunter",
    "Peaky Blinders",
    "Better Call Saul",
    "Dexter",
    "Homeland",
    "Money Heist (La Casa de Papel)",
    "The Witcher",
    "Ozark",
    "Vikings",
    "Breaking Bad",
    "The Crown",
    "Stranger Things",
    "Friends",
    "The Office",
    "Game of Thrones",
    "Lost"
];

